spring.application.name=practica-pruebas
spring.datasource.url=jdbc:h2:mem:practica-pruebas-db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
citas.duracion.minima=15
citas.duracion.maxima=120
citas.horaMinimaCancelacion=24
citas.horarioLaboral.horaInicio=9
citas.horarioLaboral.horaFin=18

